/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ro.uoradea.ieti.sd.labs;

import org.junit.jupiter.api.Test;

import ro.uoradea.ieti.sd.labs.App;

import static org.junit.jupiter.api.Assertions.*;

import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void generatedKeyHasCorrectLength() throws NoSuchAlgorithmException {
        SecretKey key = App.generateKey(128);
        assertEquals(128, key.getEncoded().length * 8);
    }

    @Test void generatedKeyHasCorrectAlgo() throws NoSuchAlgorithmException {
        SecretKey key = App.generateKey(128);
        assertEquals("AES", key.getAlgorithm());
    }

    @Test void generatedIVHasTheCorrectLength() {
        IvParameterSpec iv = App.generateIV();
        assertEquals(128, iv.getIV().length * 8);
    }

    @Test void decryptionOfCipherTextShouldReturnOriginal() throws NoSuchAlgorithmException, InvalidKeyException, NoSuchPaddingException, InvalidAlgorithmParameterException, IllegalBlockSizeException, BadPaddingException {
        String input = "test";
        SecretKey key = App.generateKey(128);
        IvParameterSpec iv = App.generateIV();
        String algo = "AES/CBC/PKCS5Padding";
        String cipherText = App.encrypt(algo, input, key, iv);
        String decrypted = App.decrypt(algo, cipherText, key, iv);
        assertEquals(input, decrypted);
    }
}
